### PR TITLE
ROMs: Add nlos.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by msfjarvis — CHANGES_REQUESTED** [review]
Add a link to this in [SupportedROMs.md](https://github.com/substratum/documentation/blob/master/Oreo/User/SupportedROMs.md)

**Comment by msfjarvis** [comment]
Why did you close this? 😐

**Comment by ghost** [comment]
Created a new one, containing the entry to SupportedROMs.md. The new request also contains two fixes.

Sorry, if this messes your workflow. I've thought a new, clean one would be better.

**Comment by msfjarvis** [comment]
If I needed a new one I'd have closed this myself.

**Pull request closed without merging**
