### PR TITLE
Update BuildingSubstratum.md

### PR DESCRIPTION
**Pull request by danparidae**

### CODE REVIEW

**Comment by nathanchance** [comment]
This doesn't work on Windows, please read the note at the top of this section as I already covered this.

**Comment by danparidae** [comment]
Now I see. However compiling on windows sounds sad. Should edit the note to remove ./ On windows as I think majority uses Linux for this stuff

**Comment by nathanchance** [comment]
I can agree with that. Updated the logic to cater to Linux users first. Thanks!

**Comment by danparidae** [comment]
Nice ;)

**Pull request merged**
